language: csharp
mono:
  - latest

solution: MineLib.Core.sln

install:
  - nuget restore MineLib.Core.sln

script:
  - xbuild /p:Configuration=Release MineLib.Core.sln
  - xbuild /p:Configuration=Debug MineLib.Core.sln

notifications:
  email:
    on_success: always
