os: Visual Studio 2015
configuration:
- Debug
- Release
platform: Any CPU
install:
- git submodule update --init --recursive
build:
  project: MineLib.Core.sln
before_build:
- nuget restore
build:
  verbosity: minimal
